### ISSUE TITLE
I'd love to have a coc.nvim extension alongside the vscode one

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#17]
AFAIK, it's little to nothing to create an [coc.nvim](https://github.com/neoclide/coc.nvim) extension from vscode one. Basically you need to change imports "[vscode](https://www.npmjs.com/package/vscode-languageclient)" to "[coc.nvim](https://www.npmjs.com/package/coc.nvim)". [coc.nvim](https://github.com/neoclide/coc.nvim) is and extension for vim/neovim to provide LSP.

**Comment by jemc** [comment]
Does it make sense to create a new `tooling/vim` subdirectory in this repo, or are the differences so small that we should just have a CircleCI job that copies the `tooling/vscode` subdirectory and applies a small patch to make it compatible with `coc.nvim`?

As part of this ticket, we can add a CircleCI job that auto-publishes the CoC extension to the npm registry.

**Comment by teggotic** [comment]
I can try making a copy of your extension to test it against vim. Then I'll share difference

**Comment by teggotic** [comment]
I made an almost working package for coc.nvim but it looks like it need a vim plugin too. I created one and provided basic syntax highlighting there. https://github.com/teggotic/vim-mare

**Comment by jemc** [comment]
Great! Let me know if you want to bring any of that code into this repo, or if you want to create a link in this repo that can tell people about the plugin.

**Comment by jemc** [comment]
Nevermind my previous message - I didn't see the PR yet. It's merged now.

Is there anything else that needs to be done before we close this issue ticket?

**Comment by teggotic** [comment]
@jemc maybe we can create something like organization on the github and to separate extenal tooling from this repository. I'd love to move my vim extension to the mare repo too.

**Comment by jemc** [comment]
Well part of my hope is that we could eventually remove the duplication between `tooling/vscode` and `tooling/vim` - I'd prefer them in the same repo for now, at least while the project is young, because it will reduce overhead for making changes that impact multiple subprojects.

**Comment by teggotic** [comment]
> Well part of my hope is that we could eventually remove the duplication between `tooling/vscode` and `tooling/vim` - I'd prefer them in a mono-repo for now, at least while the project is young, because it will reduce overhead for making changes that impact multiple subprojects.
> 
> There will be a lot of breaking changes on our way to language syntax and standard library stability, so I think it's important to be able to easily test and iterate on multiple parts of the project at the same time - external repos depending on eachother are more likely to go stale while the project is still in the stages of moving very fast.

Sure. Im talking about the future of it. Also I didnt mean to break vim and vscode extentions apart. We can have a single repo for them and have a submodule here.

**Comment by teggotic** [comment]
> Well part of my hope is that we could eventually remove the duplication between `tooling/vscode` and `tooling/vim` - I'd prefer them in a mono-repo for now, at least while the project is young, because it will reduce overhead for making changes that impact multiple subprojects.
Actually I didn't add much to the vim version. It shouldn't be that hard to remove duplication there. We can introduce common npm module and use it as a dependency.

**Comment by teggotic** [comment]
I'm closing this issue as it's vim extension is already there
