### ISSUE TITLE
Add Time.format function (and backing TimeFormatter class)

### ISSUE THREAD

**Issue by jemc** [jemc/mare#2]
We recently added a `Time` class inspired by that from Crystal (0f0865ab9060fdc15e9fdf146ca40947407dadc8). It's only partially implemented, and one of the major pieces of functionality still missing is parsing and printing the Time with a given format.

The scope of this ticket is to add a new `Time.format` function, including a `TimeFormatter` class to implement it.

---

### This ticket has the "help wanted" label, indicating that I'm looking for new contributors to try their hand at this. If you're interested in doing so, please comment here and I will assign you.

I'm also offering screen-sharing pairing sessions to those interested, so I can personally help you get acclimated to contributing quickly without a lot of stumbling around in the dark, and so that I can gather valuable observations about the stumbling blocks that might impact newcomers to the language. If you're interested in this, let me know and we can schedule it.

**Comment by teggotic** [comment]
Hi @jemc :hand:. I started implementing TimeFormatter
