### ISSUE TITLE
Implement Type Aliases

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#21]
Pony has syntax
```pony
type A is B
```

**Comment by jemc** [comment]
@teggotic - just to make sure - for the use cases you are picturing, you want `A` to be an alias of `B` and not a distinct type, right?

That is, you want it to work like it does in Pony, where any instance of `A` can be passed to a function or assigned to a variable that expects `B`, right?

**Comment by teggotic** [comment]
I want to implement Json like this in pony
```pony
type JsonType is (F64 | String | Map[String, JsonType] | Array[JsonType] | None) 
```

**Comment by jemc** [comment]
Yeah, that's a good, notorious example from Pony to have in my test cases while I'm working on this to make sure the compiler handles that correctly from the start.

**Comment by jemc** [comment]
This was resolved by https://github.com/jemc/mare/commit/4e6e9e1e1212bf937df2deacd71f78385fe23391

I think I accounted for most cases but there may some buggy edge cases that we'll discover as we start to use this, as it was a rather complex change.
