### ISSUE TITLE
LSP bug

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#26]
![image](https://user-images.githubusercontent.com/16068886/87224867-7a6f2500-c391-11ea-99cb-f4ccb24c105a.png)
I see this now when I open a file from the standard package

**Comment by jemc** [comment]
That's odd... that's not what the Mare compiler's parser errors look like at all. It looks like it's trying to run through some other parser, like maybe a JSON parser - are you sure you've got the Language set to Mare?

**Comment by teggotic** [comment]
For some reason I don't have such an issue after the restart. But yes, it's likely to be the JSON extention trying to parse the .mare file. Closing
