### ISSUE TITLE
Error message for None result value of while loop with no else clause

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#30]
```mare
:actor Main
  :new(env Env)
    i USize = 0

    t = while (i < 2) (
      i += 1
      "h"
    )
  
    env.out.print(Inspect[t])
```
I want t to be (String | None). But the compiler says that t value is None
![image](https://user-images.githubusercontent.com/16068886/87572882-d65ce500-c6d4-11ea-877c-596100a55c94.png)
But when I add `| i` to the while block, it compiles correctly.

**Comment by jemc** [comment]
Yeah, you need the `| i` if you want `None` to not be part of the return type.

The block will not run at all if the while iterates zero times, and the compiler has to assume that zero iterations is a possibility. So if you don't include an "else" clause (`| whatever_fallback_value_goes_here` the compiler will include `None` as a possible type.

So I think this just needs a clearer error message.

**Comment by jemc** [comment]
> I want t to be (String | None).

Sorry, I didn't see this part of what you wrote at first.

Yes, the type of the while actually is `(String | None)` - the compiler typechecks each branch separately, so you see an error just for the branch that failed (which has a type of `None`) even though the whole expression ends up as `(String | None)`. Which is made more confusing by the fact that it's checking the implicit branch, where the position it shows falls back to the entire loop expression (because the implicit branch has no real visible position).

I will make the error message for this more clear so that it tells you that it is specifically talking about the implicit "else" branch.

**Comment by jemc** [comment]
The fact that `None` is not a subtype of `Any'box` is another annoyance I need to resolve - it should be possible to inspect a `None` but at this time it is not.

**Comment by teggotic** [comment]
Bunch of issues :upside_down_face:

**Comment by jemc** [comment]
Indeed, but I believe I resolved all of them last night after reading this :smiley: 

### `None` (along with all other primitives) is now inspectable:

```mare
:actor Main
  :new (env)
    array Array((String | U64 | None)) = ["Hello", "World!", 1, 2, 3, None]
    env.out.print(Inspect[array]) // prints: ["Hello", "World!", 1, 2, 3, None]

    i = USize[2]
    maybe_string = while (i > 0) (i -= 1, "It ran at least once")
    env.out.print(Inspect[maybe_string]) // prints: "It ran at least once"

    maybe_string = while (i > 0) (i -= 1, "It ran at least once")
    env.out.print(Inspect[maybe_string]) // prints: None

```

### A clearer error message is used for the implicit "else" branch

```mare
Compilation Error:

The type of this expression doesn't meet the constraints imposed on it:
from /opt/code/examples/test.jemc/main.mare:37:
    string = while (i > 0) (i -= 1, "It ran at least once")
             ^~~~~

- it is required here to be a subtype of String:
  from /opt/code/examples/test.jemc/main.mare:38:
    env.out.print(string)
                  ^~~~~~

- but the type of the loop's result when it runs zero times was None:
  from /opt/code/examples/test.jemc/main.mare:37:
    string = while (i > 0) (i -= 1, "It ran at least once")
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
