### ISSUE TITLE
Add tuples

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#36]

**Comment by jemc** [comment]
I have just added a stack-allocated value types (declared via `:struct`) which have semantics very similar to tuples, but must be declared ahead of time, can have methods, can have ref caps, and all the elements must have names.

Currently I'm thinking this mostly fills the niche of what a tuple is supposed to do. It's not quite the same, but it's close enough that I'd like to close this ticket for now until more need is expressed to prompt re-opening the discussion.
