### ISSUE TITLE
0.4.3 version of vscode extension is not working

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#38]
![image](https://user-images.githubusercontent.com/16068886/88215629-a24d6b00-cc64-11ea-85ec-d878ecd222a3.png)

**Comment by jemc** [comment]
Yeah, I see this error too, and not sure why... Let's bump the version and see what happens.

**Comment by jemc** [comment]
Version 0.4.4 (just published) is also failing...

I'm not sure what the issue is.

**Comment by teggotic** [comment]
0.4.2 is working but can't support new features of LSP server

**Comment by jemc** [comment]
Tried to fix it by adding `npm run-script compile` to the CircleCI config and publishing a new version (0.4.5), but the new version is also broken in the same way...

**Comment by teggotic** [comment]
It seems like we don't have `out` folder when extension is loaded to the vscode.

**Comment by jemc** [comment]
Really? I see it there when I look at `~/.vscode/extensions/mare-lang.mare-0.4.5/out/` after installing the extension. Where are you looking when you see that it's missing?

**Comment by teggotic** [comment]
Maybe fixed
