### ISSUE TITLE
Add compiler flag to enable/disable LLVM optimizations

### ISSUE THREAD

**Issue by jemc** [jemc/mare#46]
Ponyc has `release` and `debug` mode of compiling:
- `release` takes longer to compile because it does LLVM optimizations, but the binary program it produces is more optimized
- `debug` compiles faster because it skips LLVM optimizations, but the binary program it produces is thus less optimized

Currently Mare always skips LLVM optimizations.

We should add a compiler flag that lets the user enable/disable LLVM optimizations so that we have a way to produce "fast"/optimized binaries.

This would let us subsequently start to analyze where we may be able to improve our `CodeGen` pass to produce code that is friendlier to LLVM optimizations, by finding code that currently doesn't optimize very well. This is the next step to proving that Mare is a high-performance programming language.

**Comment by jemc** [comment]
A few thoughts on this ticket:

- We can look at how Crystal does LLVM optimizations in their compiler, and try to piggyback on the same method, because I am assuming they have C FFI wrappers for methods they use.

- Pony currently uses C++ code for LLVM optimizations, in part because it has custom LLVM optimization passes, implemented as C++ classes. Eventually we would probably want the same custom LLVM passes, so it's worth considering how we might do this - do we need to compile a small C++ static library and link it into the Mare compiler? We don't need these custom

**Comment by teggotic** [comment]
> * Pony currently uses C++ code for LLVM optimizations, in part because it has custom LLVM optimization passes, implemented as C++ classes. Eventually we would probably want the same custom LLVM passes, so it's worth considering how we might do this - do we need to compile a small C++ static library and link it into the Mare compiler? We don't need these custom passes immediately for this ticket, but we will want them eventually.
Could you reference these files?

**Comment by jemc** [comment]
I believe it all happens in `genopt.cc`.

For example, here is the custom `HeapToStack` optimization pass: https://github.com/ponylang/ponyc/blob/0d5185441afd4fed1017430e7af89128969ebdc2/src/libponyc/codegen/genopt.cc#L90

**Comment by teggotic** [comment]
I added LLVM optimizations, but they are taking 0.1 to run. Seems a bit strange. We need benchmarks maybe?

**Comment by teggotic** [comment]
Seems like we have not so much code yet :smile:

**Comment by jemc** [comment]
Yeah, I'll be curious to see how much the code is getting optimized. Thanks for working on this. I may take a look at the optimized IR later for a few different example programs and see if things are getting optimized like I hope (for example, I'm hoping that `Count.to` and similar yield blocks can be optimized to be just as fast and simple in the final code as a `while` loop, but that may take more tuning of the IR we are generating to make it more optimization-friendly).
