### ISSUE TITLE
Encore

### ISSUE THREAD

**Issue by benman1** [jemc/mare#5]
Hi
I am still reading up on Pony, and - while there's not much software written in it - I've come across Mare and Encore, two languages based on Pony. I am really curious what you think about [Encore](https://github.com/parapluu/encore), written at Uppsala University?
Thanks!
Ben.

**Comment by jemc** [comment]
I personally don't have much of an opinion on Encore because I haven't looked into it or used it. The Pony runtime is excellent, so in general I think it's great to have multiple languages using it with varying approaches.
