### ISSUE TITLE
Compiler falsely claims that a variable just initialized in a try block may already be consumed

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#58]
![image](https://user-images.githubusercontent.com/16068886/89127568-0985dd80-d4f7-11ea-8661-f8fab7865ebb.png)
![image](https://user-images.githubusercontent.com/16068886/89127571-10145500-d4f7-11ea-92d4-77b8f0d42714.png)

**Comment by jemc** [comment]
Better control flow analysis will help this bug, so I'm marking this ticket as blocked by this other one: https://github.com/jemc/mare/issues/75

**Comment by jemc** [comment]
This was fixed as part of the work done for #75, which is now finished.

The above example now compiles without error, as intended.
