### ISSUE TITLE
Add instructions/changes needs to use Mare outside of Docker

### ISSUE THREAD

**Issue by jemc** [jemc/mare#91]
At the start of this project, I saw Docker as an easy shortcut for pulling together the correct versions of all of Mare's dependencies in a consistent repeatable environment across platforms.

However, the Docker delivery mechanism has a few shortcomings:
- Dealing with source code files on the host file system is awkward - they need to be mounted as a volume, and thus they have a different path in the compiler's view than they had in the host system, leading to potential confusion for both humans and tools (like VSCode, LLDB, etc, where we need to correlate the mounted source path to the host source path)
- Docker is not available on all platforms (e.g. FreeBSD)

For these reasons, we want to create a path for building and using the Mare compiler outside of Docker. Eventually, this may become the main path if we can build via CI automation some convenient distributable packages for the major platforms (various Linux distros, MacOS via Homebrew, eventually Windows as well, etc).

However, for the purposes of this ticket, we want to create a markdown document and/or Makefile automation for building Mare and acquiring its dependencies on various platforms. For now this document will remain a best effort for various platforms it mentions, rather than an officially guaranteed path.

Here are the dependencies that are needed:
- Crystal compiler version 1.0.0
- Pony runtime bitcode, built from a specific git revision (see the Dockerfile), compiled into bitcode for the native platform using the same LLVM version that Crystal was built with (see `crystal --version`)
- (eventually the Verona runtime will be an optional alternative for the Pony runtime, but for now let's ignore that because Mare support for Verona is very, very limited at the moment)

There may also be code changes need. For example, we may need to accept an environment variable that points the Mare compiler to the path of the `libponyrt.bc` file for the Pony runtime bitcode, so that it can join the LLVM module for the user program to that one for the runtime.

**Comment by jemc** [comment]
@mneumann - As we discussed in #87, I have opened this ticket to track this work.

I've invited you as a collaborator to this repo so that I can assign this ticket to you if you're interested in working on it for FreeBSD, then I can help you if you get stuck, and I and others can expand it for other platforms in time.

Let me know if you're interested.

**Comment by mneumann** [comment]
@jemc great. where is the best place to ask you questions about libponyrt?

* I would like to get Mare working with an unpatched libponyrt if possible.
* I see `mare/ponypatches`... would be nice to get things integrated into ponyc upstream. Are these patches still required? Pony is now at version 0.41.x.
* I see that you are commenting out the `Main_runtime_override_defaults_oo` function via `'s/void Main_/\/\/ void Main_/g`. I am wondering whether it would be easier to provide a dummy function at link time instead.

**Comment by jemc** [comment]
> where is the best place to ask you questions about libponyrt?

We can discuss here in the ticket, or chat via DM in realtime at https://ponylang.zulipchat.com/ - whatever you prefer, as I should be responsive in both venues.

> I would like to get Mare working with an unpatched libponyrt if possible.

Yeah, that's a good goal. Let's look at the patches we currently have:

- https://github.com/jemc/mare/blob/master/ponypatches/realloc_fix.patch - This is just mirroring a patch that was applied in upstream Pony without needing to actually update our Pony version, because I was wanting a quick fix. However, I agree with you that it would be good for us to update to the latest Pony version. When we have the latest Pony version, this particular patch won't be needed.

- https://github.com/jemc/mare/blob/master/ponypatches/alpine_libponyrt.patch - I don't know the full details of this one because it wasn't me who added it. If it's still necessary after updating Pony versions, we can figure out how to get some version of it merged in upstream.

> I see that you are commenting out the `Main_runtime_override_defaults_oo` function via `'s/void Main_/\/\/ void Main_/g`. I am wondering whether it would be easier to provide a dummy function at link time instead.

Yes, I agree that we should make a dummy function. I can handle this in a quick PR of my own so that you shouldn't have to mess with any of our codegen stuff.

**Comment by mneumann** [comment]
Great, btw, got it to work on FreeBSD. `mare/compiler/binary.cr` needs some minor patching regarding the linker arguments:

Remove `-latomic`, add `-execinfo -lelf`.

You probably need platform dependent linker arguments.

Producing the patched `libponyrt.bc` was a bit of a mess. I have to write the individual steps down or patch the FreeBSD ports definition so that it is built and shipped by default.

**Comment by jemc** [comment]
> You probably need platform dependent linker arguments.

Yeah, I think in the long run we need to:
- :one: detect the host triple, hopefully using something built in to Crystal/LLVM
- :two: allow the caller to specify a target triple that is different from the host triple for cross-compiling
- :three: use different link args based on the target triple.

For now it would probably be sufficient to just do :one: and :three: and tackle cross-compiling later.

---

> I have to write the individual steps down or patch the FreeBSD ports definition so that it is built and shipped by default.

Yes, it would be great to get it shipped by default for Pony, and we can just leverage that from Mare.
